# Generated by Django 3.1 on 2020-10-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201022_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='safety_rating',
            new_name='safetyrating',
        ),
    ]
