# Generated by Django 3.1 on 2020-10-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201027_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='customer',
            new_name='user',
        ),
    ]
