# Generated by Django 3.1 on 2020-11-06 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderroom',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
