# Generated by Django 3.1 on 2020-11-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201106_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderroom',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
