# Generated by Django 3.1 on 2020-11-06 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201106_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderroom',
            name='start_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
